"""
FinAI Researcher Service - Investment Advice Agent
FastAPI application that runs a Playwright browser agent to research
investment topics, generate advice reports, and index findings.
"""

import logging
import os
from datetime import UTC, datetime
from typing import Optional

from agents import Agent, Runner, trace
from agents.extensions.models.litellm_model import LitellmModel
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

# Suppress verbose library logs to keep standard output cleaner.
# logging.basicConfig defines the general log settings for the entire application.
logging.basicConfig(level=logging.INFO)

# log.setLevel(logging.CRITICAL) suppresses log messages. In Python logging:
# DEBUG < INFO < WARNING < ERROR < CRITICAL.
# By setting LiteLLM to CRITICAL, we only show critical system failures and suppress 
# all intermediate logging (like verbose HTTP request logs or API token details).
logging.getLogger("LiteLLM").setLevel(logging.CRITICAL)
logging.getLogger("openai").setLevel(logging.ERROR)
logging.getLogger("agents").setLevel(logging.ERROR)

# logging.getLogger(__name__) gets or creates a Logger object named after the current file.
# If this file runs directly (e.g. `python server.py`), __name__ is "__main__". 
# If it is imported, __name__ is "server". This scope ensures you can see exactly 
# which module printed a log message in CloudWatch.
logger = logging.getLogger(__name__)

# Import configurations, local tools, and browser servers
from context import DEFAULT_RESEARCH_PROMPT, get_agent_instructions
from mcp_servers import create_playwright_mcp_server
from tools import ingest_financial_document

# Load operating system level configuration variables
load_dotenv(override=True)

# Register Langfuse callbacks if monitoring secrets are configured.
# LiteLLM automatically intercepts Bedrock completions and publishes statistics.
if os.getenv("LANGFUSE_SECRET_KEY"):
    try:
        import litellm
        litellm.success_callback = ["langfuse"]
        logger.info("✅ Observability: LiteLLM Langfuse callback enabled successfully")
    except Exception as e:
        logger.error(f"❌ Observability: Failed to initialize LiteLLM Langfuse hook: {e}")

# Initialize FastAPI application instance
app = FastAPI(title="FinAI Researcher Service")


# Pydantic's BaseModel is used by FastAPI to validate, deserialize, and document the API schema.
# When a client makes a POST request, FastAPI parses the JSON body, verifies it matches this schema, 
# and automatically converts it into a Python object.
class ResearchRequest(BaseModel):
    """Pydantic model representing incoming research POST API requests."""
    # Optional[str]: specifies the value must be a string or None.
    # Field(None, ...): sets a default value of None and attaches metadata/description.
    topic: Optional[str] = Field(None, description="Optional investment topic or ticker to search for.")


async def run_research_agent(topic: Optional[str] = None) -> str:
    """
    Spawns and executes the browser-equipped research agent.
    
    Args:
        topic: The search topic target.
        
    Returns:
        Final research text results generated by the LLM.
    """
    # Build query task depending on request topic
    query = (
        f"Research this investment topic: {topic}" if topic else DEFAULT_RESEARCH_PROMPT
    )
    logger.info("Starting research agent task for topic: %s", topic or "Trending topics")

    # Set up Bedrock AWS region variables for boto3 client
    region = os.environ.get("BEDROCK_REGION", "us-west-2")
    os.environ["AWS_REGION_NAME"] = region
    os.environ["AWS_REGION"] = region
    os.environ["AWS_DEFAULT_REGION"] = region

    # Initialize model using LiteLLM Bedrock connector
    model_name = os.environ.get("RESEARCHER_MODEL", "bedrock/moonshotai.kimi-k2.5")
    model = LitellmModel(model=model_name)

    # trace context manager: groups all LLM completions inside a single Langfuse trace window
    with trace("Researcher"):
        # create_playwright_mcp_server context manager: spawns Playwright Chromium process,
        # keeping it alive during agent execution and shutting it down cleanly upon exit.
        async with create_playwright_mcp_server(timeout_seconds=120) as playwright_mcp:
            agent = Agent(
                name="FinAI Investment Researcher",
                instructions=get_agent_instructions(),
                model=model,
                tools=[ingest_financial_document],
                mcp_servers=[playwright_mcp],
            )

            try:
                # Start agent loop execution (limited to maximum 15 turns)
                result = await Runner.run(agent, input=query, max_turns=15)
                return result.final_output
            except Exception as e:
                logger.error("Research agent execution failed: %s", e)
                raise
            finally:
                # Flush the Langfuse telemetries queue.
                # Lambda freezes container environments immediately upon returning HTTP requests;
                # calling flush forces asynchronous telemetry logs to upload before freeze.
                if os.getenv("LANGFUSE_SECRET_KEY"):
                    try:
                        from langfuse import Langfuse
                        Langfuse().flush()
                        logger.info("Observability: Langfuse client logs flushed successfully")
                    except Exception as e:
                        logger.warning(f"Observability: Failed to flush Langfuse queue: {e}")


@app.get("/")
@app.get("/health")
async def health():
    """Health check endpoint validating service status."""
    return {
        "service": "FinAI Researcher",
        "status": "healthy",
        "timestamp": datetime.now(UTC).isoformat(),
    }


@app.post("/research")
async def research(request: ResearchRequest) -> str:
    """
    Main endpoint triggering research agent executions.
    The agent scrapes search results, compiles statistics, and saves them.
    """
    try:
        return await run_research_agent(request.topic)
    except Exception as e:
        logger.error(f"Error executing /research endpoint: {e}")
        raise HTTPException(status_code=500, detail=str(e))
